= scala-csvreader

Scala CSV file (stream) reader

== Build status

Master: image:https://travis-ci.org/ysden123/scala-csvreader.svg?branch=master[Build Status: master,link=https://travis-ci.org/ysden123/scala-csvreader]

Develop: image:https://travis-ci.org/ysden123/scala-csvreader.svg?branch=develop[Build Status: develop,link=https://travis-ci.org/ysden123/scala-csvreader]

== CsvReader

CsvReader is simple CSV file reader with pure Scala.

The reader supports:

* arbitrary case class for record data
* file with or without header line
* setting either continue or stop after error during parsing a record
* setting different delimiter character
* error handling
* record handling

== Usage
=== Record Data Class
Record data class is a case class. For example:
[source,scala]
----
case class TestData1(i: Int, s: String, d: Double)
----
Some parameters may be Option, For example
[source,scala]
----
case class TestData2(i: Int, s: Option[String], d: Double) {
  def this(params: Seq[String]) {
    this(params(0).toInt,
      if (params(1).isEmpty)
        None
      else
        Some(params(1)),
      params(2).toDouble
    )
  }
}
----
Note in this case the auxiliary constructor should be defined!

== How to work with CsvReader
[source,scala]
----
    def recordHandler(record:TestData]:Unit={
    ...
    }

    def errorHandler(error:String]:Unit={
    ...
    }

    CsvReader.reader[TestData](Source.fromFile("data.csv"), recordHandler, errorHandler)
      .parse()
----

Use modificators:

* withDelimiter
* withContinueOnError
* withHeaderLine
* withCustomTransformer

== How to work with custom transformer
Custom transformer allows to customize creating an object.

recordHandler method should be called for each created object.

errorHandler method should be called for each error during creating object.

Example:
[source,scala]
----
    def transformer(line: Seq[String], recordHandler: TestData1 => Unit, errorHandler: String => Unit): TestData1 = {
        try {
          val data = TestData1(333, "test", 77.12)
          recordHandler(data)
          data
        } catch {
          case e: Exception =>
            errorHandler(e.getMessage)
            throw e
       }
    }
----

See CsvReaderTest test("customTransformer") and test("customTransformer with error")


